import torch
from torch.utils.data import DataLoader, Dataset
from transformers import (
    AutoTokenizer,AutoConfig,
    AutoModelForSequenceClassification, # Discriminative Fine-tuning with linear Head
    AutoModelForCausalLM, DataCollatorForLanguageModeling,# Generative Fine-tuning
    AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq,
    TrainingArguments, Trainer, EvalPrediction, EarlyStoppingCallback
)

from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix
import numpy as np
from pathlib import Path
from typing import Dict, Any, List, Tuple
import json
from tqdm import tqdm
from .config import ExperimentConfig
from .data_utils import load_split_data, prepare_model_inputs, get_label_names, get_task_prompt
from .utils import save_checkpoint, load_checkpoint

class TextDataset(Dataset):
    """Dataset for discriminative classification tasks."""
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx].clone().detach() if torch.is_tensor(val[idx]) else torch.tensor(val[idx]) 
                for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

class GenerativeDataset(Dataset):
    """Dataset for generative LLMs where labels are strings or tokenized sequences."""
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        # In causal LLM, labels are typically generated by shifting input_ids.
        # If labels are None, DataCollatorForLanguageModeling will handle this automatically.
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx].clone().detach() if torch.is_tensor(val[idx]) else torch.tensor(val[idx])
                for key, val in self.encodings.items()}
        # For generative SFT, labels are often the same as input_ids for CausalLM
        # or specific target tokens.
        if self.labels is not None:
            item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(next(iter(self.encodings.values())))

def compute_metrics(eval_pred: EvalPrediction) -> Dict[str, float]:
    # Note: not applicable for generative models
    predictions, labels = eval_pred

    # Ensure predictions is the actual logits array, in case the model outputted more
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    predictions = np.argmax(predictions, axis=1)

    accuracy = accuracy_score(labels, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='weighted')

    return {
        'accuracy': accuracy,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

def train_model(model_name: str, train_dataset: Dataset, eval_dataset: Dataset,
                output_dir: Path, num_labels: int, learning_rate: float = 2e-5,
                batch_size: int = 128, num_epochs: int = 8, seed: int = 42,
                early_stopping_patience: int = 2, gradient_accumulation_steps: int = 16,
                resume_from_checkpoint: str = None,
                # LoRA parameters
                use_lora: bool = False,
                lora_r: int = 8,
                lora_alpha: int = 32,
                lora_dropout: float = 0.05,
                # Note: BERT/RoBERTa attention layers are usually named ["query", "value"]
                # Llama/Qwen attention layers are usually named ["q_proj", "v_proj"]
                # When set to None, PEFT will automatically infer target_modules based on model architecture
                lora_target_modules: List[str] = None
                ) -> Dict[str, Any]:
    # Discriminative Fine-tuning
    torch.manual_seed(seed)
    np.random.seed(seed)

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    # Ensure pad token is set (critical for Qwen/Llama)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    print(f"num_labels: {num_labels}")
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels
    )

    # Update model config with pad token if needed
    if model.config.pad_token_id is None:
        model.config.pad_token_id = tokenizer.pad_token_id

    # Enable gradient checkpointing requires disabling cache
    if hasattr(model.config, "use_cache"):
        model.config.use_cache = False

    if use_lora:
        try:
            from peft import LoraConfig, get_peft_model, TaskType
        except ImportError:
            raise ImportError("use_lora=True requires 'peft' library. Please install it with `pip install peft`.")

        if lora_target_modules is None or lora_target_modules == "all-linear":
            import torch.nn as nn
            lora_module_names = set()
            for name, module in model.named_modules():
                # Only add LoRA to linear layers
                if isinstance(module, nn.Linear):
                    # Explicitly exclude classification head and pooling layers to completely avoid conflicts with modules_to_save!
                    # Different models may have classification heads named classifier, score, pooler, or out_proj
                    if any(exclude in name.lower() for exclude in ["classifier", "score", "pooler", "out_proj"]):
                        continue
                    # Extract specific layer names (e.g., 'encoder.layer.0.attention.self.query' -> 'query')
                    names = name.split('.')
                    lora_module_names.add(names[-1])

            lora_target_modules = list(lora_module_names)
            if not lora_target_modules:
                raise ValueError("Could not find any linear layers to attach LoRA to. Please check the model architecture.")
        print(f"Applying LoRA to Discriminative Model: r={lora_r}, alpha={lora_alpha}, targets={lora_target_modules}")

        # When gradient checkpointing is enabled, we need to allow inputs to require gradients
        if hasattr(model, "enable_input_require_grads"):
            model.enable_input_require_grads()

        peft_config = LoraConfig(
            task_type=TaskType.SEQ_CLS, # Key: specify as sequence classification task
            inference_mode=False,
            r=lora_r,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
            bias="none",
            target_modules=lora_target_modules,
            # TaskType.SEQ_CLS will automatically add the final classification head (classifier or score) to modules_to_save
            # exclude_modules=["classifier", "score", "pooler"],
            # Ensure classification head weights are trained and saved properly even with small samples
        )

        model = get_peft_model(model, peft_config)
        model.print_trainable_parameters()

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        num_train_epochs=num_epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=64,    # [Reduced] Eval batch size can usually be smaller than training
        gradient_accumulation_steps=gradient_accumulation_steps,
        learning_rate=learning_rate,
        #warmup_steps=500,
        warmup_ratio=0.1,
        weight_decay=0.01,
        logging_dir=str(output_dir / 'logs'),
        logging_steps=100,
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=1,
        load_best_model_at_end=True if not use_lora else False,
        metric_for_best_model="accuracy",
        greater_is_better=True ,
        seed=seed,
        fp16=torch.cuda.is_available(),
        gradient_checkpointing=True,     # Saves massive amount of VRAM
        # ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,

        eval_accumulation_steps=4,       # Transfer eval results to CPU every 1 step to prevent VRAM overflow
        #optim="adamw_torch",             # Use more stable optimizer
        #group_by_length=True,            # Group samples with similar lengths together to reduce padding waste

        # Force single-GPU training (disable DDP)
        local_rank=-1,  # Explicitly disable DDP
        ddp_find_unused_parameters=False,
        dataloader_pin_memory=True,  # Speed up data loading
        remove_unused_columns=False,
    )

    callbacks = []
    if early_stopping_patience > 0 and not use_lora:
        callbacks.append(EarlyStoppingCallback(early_stopping_patience=early_stopping_patience))

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        processing_class=tokenizer,
        compute_metrics=compute_metrics,
        callbacks=callbacks,
    )
    
    trainer.train(resume_from_checkpoint=resume_from_checkpoint) if resume_from_checkpoint is not None else trainer.train()
    eval_results = trainer.evaluate()

    trainer.save_model(str(output_dir))
    tokenizer.save_pretrained(str(output_dir))


    return {
        "model_path": str(output_dir),
        "eval_results": eval_results,
        "training_args": training_args.to_dict()
    }

# New training metric helper functions for generative models
def compute_generative_metrics(eval_preds):
    preds, labels = eval_preds
    # preds are already argmax results with shape [batch_size, seq_len]

    # === Core fix: Shift operation for CausalLM ===
    # if not is_encoder_decoder:
    # Discard the last prediction as there is no corresponding next token label
    preds = preds[:, :-1]
    # Discard the first label as it corresponds to prediction without context
    labels = labels[:, 1:]
    # ============================================

    # Flatten
    labels = labels.reshape(-1)
    preds = preds.reshape(-1)

    # Filter out padding and tokens ignored during loss calculation (-100)
    mask = labels != -100
    labels = labels[mask]
    preds = preds[mask]

    if len(labels) == 0:
        return {"accuracy": 0.0}

    # Calculate Next-Token Accuracy
    accuracy = (preds == labels).astype(np.float32).mean().item()
    return {"accuracy": accuracy}

def preprocess_logits_for_metrics(logits, labels):
    if isinstance(logits, tuple):
        # Depending on the model and config, logits may contain extra tensors,
        # like past_key_values, but usually the first element is the actual logits.
        logits = logits[0]
    return logits.argmax(dim=-1)

def train_generative_model(model_name: str, train_dataset: Dataset, eval_dataset: Dataset,
                         output_dir: Path, learning_rate: float = 2e-5,
                         batch_size: int = 64, num_epochs: int = 7,
                         seed: int = 42,
                         tokenizer: AutoTokenizer = None,
                         early_stopping_patience: int = 2,
                         resume_from_checkpoint: str = None,
                         # lora parameters defaultly unused
                         use_lora: bool = False,
                         lora_r: int = 8,
                         lora_alpha: int = 32,
                         lora_dropout: float = 0.05,
                         lora_target_modules: List[str] = ["q_proj", "v_proj"]
                         ) -> Dict[str, Any]:
    torch.manual_seed(seed)
    print(f"Training generative model: {model_name} | LoRA: {use_lora}")
    tokenizer = AutoTokenizer.from_pretrained(model_name, fix_mistral_regex=True) if tokenizer is None else tokenizer
    # NOTE: Use left padding for generation during inference and right padding for training
    tokenizer.padding_side = "right"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # 1. Load as CausalLM instead of Classification
    if resume_from_checkpoint is None:
        config = AutoConfig.from_pretrained(model_name)
        if getattr(config, "is_encoder_decoder", False):
            print("Detected encoder-decoder architecture (e.g., BART/T5). Using AutoModelForSeq2SeqLM.")
            model = AutoModelForSeq2SeqLM.from_pretrained(
                model_name,
                dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float32,
                device_map="auto",
                trust_remote_code=True
            )
            is_encoder_decoder = True
        else:
            print("Detected decoder-only architecture. Using AutoModelForCausalLM.")
            model = AutoModelForCausalLM.from_pretrained(
                model_name,
                dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float32,
                device_map="auto",
                trust_remote_code=True
            )
            is_encoder_decoder = False
    else:
        print(f"Resuming training from checkpoint: {resume_from_checkpoint}")
        config = AutoConfig.from_pretrained(resume_from_checkpoint)
        if getattr(config, "is_encoder_decoder", False):
            model = AutoModelForSeq2SeqLM.from_pretrained(resume_from_checkpoint)
            is_encoder_decoder = True
        else:
            model = AutoModelForCausalLM.from_pretrained(resume_from_checkpoint)
            is_encoder_decoder = False

    model.gradient_checkpointing_enable()
    model.config.use_cache = False

    # === LoRA configs ===
    if use_lora:
        try:
            from peft import LoraConfig, get_peft_model, TaskType
        except ImportError:
            raise ImportError("use_lora=True requires 'peft' library. Please install it with `pip install peft`.")

        print(f"Applying LoRA: r={lora_r}, alpha={lora_alpha}, targets={lora_target_modules}")

        # Key: When gradient checkpointing is enabled, we need to allow inputs to require gradients, otherwise LoRA will error
        if hasattr(model, "enable_input_require_grads"):
            model.enable_input_require_grads()

        peft_task_type = TaskType.SEQ_2_SEQ_LM if is_encoder_decoder else TaskType.CAUSAL_LM

        peft_config = LoraConfig(
            task_type=peft_task_type,
            inference_mode=False,
            r=lora_r,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
            bias="none",
            target_modules=lora_target_modules
        )

        model = get_peft_model(model, peft_config)
        model.print_trainable_parameters()
    # 2. Use DataCollator for Completion
    # This automatically handles shifting inputs for next-token prediction, mlm=False
    if is_encoder_decoder:
        # For BART/T5: typically dataset should pre-prepare input_ids / attention_mask / labels
        # Here we assume GenerativeDataset has already placed labels inside; collator handles padding and sets pad_label to -100
        data_collator = DataCollatorForSeq2Seq(
            tokenizer=tokenizer,
            model=model,
            label_pad_token_id=-100
        )
    else:
        # Decoder-only: autoregressive LM, input_ids shifted right as labels
        data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        num_train_epochs=num_epochs,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=16,
        learning_rate=learning_rate,
        logging_steps=10,
        eval_strategy="epoch",
        # eval_steps=100,
        save_strategy="epoch",
        save_total_limit=5,
        load_best_model_at_end=True,
        metric_for_best_model="accuracy", # from eval_loss to accuracy
        greater_is_better=True,           # accuracy greater is better (loss smaller is better)
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        gradient_checkpointing=True,
        report_to="none",
        # For encoder-decoder, if you need metrics based on generated text later, you can enable:
        # predict_with_generate=True,
    )
    callbacks = []
    if early_stopping_patience > 0:
        callbacks.append(EarlyStoppingCallback(early_stopping_patience=early_stopping_patience))

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        data_collator=data_collator,
        callbacks=callbacks,
        # === Pass Metrics functions ===
        compute_metrics=compute_generative_metrics,
        preprocess_logits_for_metrics=preprocess_logits_for_metrics,
    )

    trainer.train()
    trainer.save_model()

    # Additionally save tokenizer for convenient loading during inference
    tokenizer.save_pretrained(output_dir)
    return {"status": "success", "output_dir": str(output_dir)}

def evaluate_model(model_path: Path, eval_items: List[Dict[str, Any]],
                   task: str, batch_size: int = 32,
                   is_generative: bool = False) -> Dict[str, Any]:

    tokenizer = AutoTokenizer.from_pretrained(model_path, fix_mistral_regex=True)

    if is_generative:
        tokenizer.padding_side = "left"
        model = AutoModelForCausalLM.from_pretrained(model_path)
    else:
        model = AutoModelForSequenceClassification.from_pretrained(model_path)

    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available()
                          else "mps" if torch.backends.mps.is_available()
                          else "cpu")
    model = model.to(device)

    all_predictions = []
    all_predicted_labels = []
    all_labels = []

    num_batches = (len(eval_items) + batch_size - 1) // batch_size
    for i in tqdm(range(0, len(eval_items), batch_size), total=num_batches, desc="Evaluating"):
        batch_items = eval_items[i:i+batch_size]

        #encodings, labels = prepare_model_inputs(
        #    batch_items, tokenizer, is_generative=is_generative, task=task
        #)
        #print(f"Labels  {labels}")
        # encodings = encodings.to(device)
        if is_generative:
            # Generative evaluation logic: Construct Prompt -> Generate -> String Match
            # 1. Construct inference prompt (without label)
            prompts = []

            label_names = get_label_names(task)
            for item in batch_items:
                text_a, text_b = item["text_a"], item.get("text_b")
                p = get_task_prompt(task, text_a, text_b)
                prompts.append(p)

            # 2. Use left padding for inference prompts
            tokenizer.padding_side = "left"
            inputs = tokenizer(prompts, return_tensors="pt", padding=True, truncation=True, max_length=1024).to(device)

            # 3. Generate responses
            with torch.no_grad():
                generated_ids = model.generate(
                    **inputs,
                    max_new_tokens=10,
                    do_sample=False,
                    pad_token_id=tokenizer.pad_token_id,
                    eos_token_id=tokenizer.eos_token_id
                )
            # Only decode the newly generated tokens
            input_len = inputs.input_ids.shape[1]
            responses = tokenizer.batch_decode(generated_ids[:, input_len:], skip_special_tokens=True)

            for idx, res in enumerate(responses):
                res_lower = res.lower().strip()

                # --- Modification start: Find the earliest occurring label ---
                pred_idx = -1
                earliest_pos = float('inf')

                # No need to sort by length, directly iterate through all labels
                for label_id, name in enumerate(label_names):
                    pos = res_lower.find(name.lower())

                    # If this label is found and appears earlier than previously recorded position
                    if pos != -1 and pos < earliest_pos:
                        earliest_pos = pos
                        pred_idx = label_id

                # If the model outputs gibberish that doesn't contain any label, pred_idx stays -1
                # This will cause errors or anomalies when calculating metrics with sklearn.
                if pred_idx == -1:
                    pred_idx = 0  # Provide a default fallback classification
                # --- Modification end ---

                all_predictions.append(pred_idx)
                all_predicted_labels.append(pred_idx)
                all_labels.append(batch_items[idx]["label"])

        else:
            # Discriminative evaluation: Directly use model outputs
            if "bert" not in str(model_path) and task == "github":
                max_length = 1024 # 128 for sst, 1024 for github
            else:
                max_length = 128
            encodings, labels = prepare_model_inputs(
                batch_items, tokenizer, is_generative=False, task=task, max_length=max_length
            )
            encodings = encodings.to(device)
            encodings = {k: v.to(device) for k, v in encodings.items()}

            with torch.no_grad():
                outputs = model(**encodings)
                #predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
                # Use .logits to get the tensor for argmax
                logits = outputs.logits
                #print(outputs)
                predicted_labels = torch.argmax(logits, dim=-1)

            all_predictions.append(logits.cpu().numpy())
            all_predicted_labels.append(predicted_labels.cpu().numpy())
            all_labels.extend(labels)

    if is_generative:
        predictions_np = np.array(all_predictions)
        predicted_labels_np = np.array(all_predicted_labels)
    else:
        predictions_np = np.vstack(all_predictions)
        predicted_labels_np = np.concatenate(all_predicted_labels)
    labels_np = np.array(all_labels)

    accuracy = accuracy_score(labels_np, predicted_labels_np)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels_np, predicted_labels_np, average='weighted'
    )

    label_names = get_label_names(task)
    per_class_precision, per_class_recall, per_class_f1, _ = precision_recall_fscore_support(
        labels_np, predicted_labels_np, average=None
    )

    per_class_metrics = {}
    for i, label_name in enumerate(label_names):
        per_class_metrics[label_name] = {
            "precision": per_class_precision[i],
            "recall": per_class_recall[i],
            "f1": per_class_f1[i]
        }

    cm = confusion_matrix(labels_np, predicted_labels_np)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "per_class_metrics": per_class_metrics,
        "confusion_matrix": cm.tolist(),
        "predictions": predictions_np.tolist(),
        "predicted_labels": predicted_labels_np.tolist(),
        "true_labels": labels_np.tolist()
    }



def train_sft(config: ExperimentConfig, run_dir: Path) -> Dict[str, Any]:
    results = {}

    for task in config.tasks:
        task_results = {}

        fit_items = load_split_data(run_dir, task, "fit")
        dev_items = load_split_data(run_dir, task, "dev")

        num_labels = len(get_label_names(task))

        for model_name in config.models:
            model_key = model_name.replace("/", "_").replace("-", "_")

            tokenizer = AutoTokenizer.from_pretrained(model_name)

            train_encodings, train_labels = prepare_model_inputs(fit_items, tokenizer)
            dev_encodings, dev_labels = prepare_model_inputs(dev_items, tokenizer)

            train_dataset = TextDataset(train_encodings, train_labels)
            dev_dataset = TextDataset(dev_encodings, dev_labels)

            output_dir = run_dir / "models" / "sft" / task / model_key
            
            training_result = train_model(
                model_name=model_name,
                train_dataset=train_dataset,
                eval_dataset=dev_dataset,
                output_dir=output_dir,
                num_labels=num_labels,
                seed=config.seed
            )

            test_items = load_split_data(run_dir, task, "test")
            mining_items = load_split_data(run_dir, task, "mining")

            dev_metrics = evaluate_model(output_dir, dev_items, task)
            test_metrics = evaluate_model(output_dir, test_items, task)
            mining_metrics = evaluate_model(output_dir, mining_items, task)

            task_results[model_key] = {
                "training": training_result,
                "dev_metrics": dev_metrics,
                "test_metrics": test_metrics,
                "mining_metrics": mining_metrics
            }

        results[task] = task_results

    with open(run_dir / "results" / "sft_results.json", "w") as f:
        json.dump(results, f, indent=2)

    return results

def train_aft(config: ExperimentConfig, run_dir: Path) -> Dict[str, Any]:
    results = {}

    for task in config.tasks:
        task_results = {}

        fit_items = load_split_data(run_dir, task, "fit")
        dev_items = load_split_data(run_dir, task, "dev")

        default_signal = config.signals[0]
        default_strategy = config.strategies[0]
        default_threshold = config.thresholds[2]

        edits_file = (run_dir / "probes" / task /
                     f"accepted_{default_signal}_{default_strategy}_{default_threshold}.jsonl")
        
        if not edits_file.exists():
            raise FileNotFoundError(f"Accepted edits file not found: {edits_file}")

        from .utils import load_jsonl
        accepted_edits = load_jsonl(edits_file)

        augmented_items = fit_items + accepted_edits

        num_labels = len(get_label_names(task))

        for model_name in config.models:
            model_key = model_name.replace("/", "_").replace("-", "_")

            tokenizer = AutoTokenizer.from_pretrained(model_name)

            train_encodings, train_labels = prepare_model_inputs(augmented_items, tokenizer)
            dev_encodings, dev_labels = prepare_model_inputs(dev_items, tokenizer)

            train_dataset = TextDataset(train_encodings, train_labels)
            dev_dataset = TextDataset(dev_encodings, dev_labels)

            output_dir = run_dir / "models" / "aft" / task / model_key

            training_result = train_model(
                model_name=model_name,
                train_dataset=train_dataset,
                eval_dataset=dev_dataset,
                output_dir=output_dir,
                num_labels=num_labels,
                seed=config.seed
            )

            test_items = load_split_data(run_dir, task, "test")
            test_metrics = evaluate_model(output_dir, test_items, task)

            task_results[model_key] = {
                "training": training_result,
                "test_metrics": test_metrics,
                "augmentation_config": {
                    "signal": default_signal,
                    "strategy": default_strategy,
                    "threshold": default_threshold,
                    "num_augmented": len(accepted_edits)
                }
            }

        results[task] = task_results

    with open(run_dir / "results" / "aft_results.json", "w") as f:
        json.dump(results, f, indent=2)

    return results